spring.application.name=bank-products

# 1. H2
spring.datasource.primary.jdbc-url=jdbc:h2:./transaction
spring.datasource.primary.driver-class-name=org.h2.Driver
spring.datasource.primary.username=sa
spring.datasource.primary.password=
spring.datasource.primary.hikari.connection-init-sql=SET MODE READ ONLY
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 2. PostgreSQL
spring.datasource.rules.jdbc-url=jdbc:postgresql://localhost:5432/bank-rules
spring.datasource.rules.driver-class-name=org.postgresql.Driver
spring.datasource.rules.username=postgres
spring.datasource.rules.password=ojq039w4otJUIJ034tfj0g0e04036531fgdsvg

# 3. LIQUIBASE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public
spring.liquibase.enabled=true


# 4. JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# 5. TG
telegram.bot.token=8798367866:AAGibx22ZcSZ5K8i8hcLi6pm2EtXKf3QuLI
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
