spring.application.name=bank-products
spring.datasource.url=jdbc:h2:.C:./Users/??????/IdeaProjects/bank-products/bank-products/transaction.mv.db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
