spring.application.name=bank-products

# ===== ???????? ?? (H2) =====
spring.datasource.primary.jdbc-url=jdbc:h2:./transaction
spring.datasource.primary.hikari.connection-init-sql=SET MODE READ ONLY
spring.datasource.primary.driver-class-name=org.h2.Driver
spring.datasource.primary.username=sa
spring.datasource.primary.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== ?????? ?? (PostgreSQL) =====
spring.datasource.rules.jdbc-url=jdbc:postgresql://localhost:5432/bank_rules
spring.datasource.rules.driver-class-name=org.postgresql.Driver
spring.datasource.rules.username=postgres
spring.datasource.rules.password=ojq039w4otJUIJ034tfj0g0e04036531fgdsvg

# ===== LIQUIBASE =====
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public