# ===== ???????? ???? (H2 ? ??????) =====
spring.datasource.primary.jdbc-url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.primary.driver-class-name=org.h2.Driver
spring.datasource.primary.username=sa
spring.datasource.primary.password=

spring.datasource.rules.jdbc-url=jdbc:h2:mem:rules;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.rules.driver-class-name=org.h2.Driver
spring.datasource.rules.username=sa
spring.datasource.rules.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect